Added option to edit role
bigbinary/neeto-team-members pull request #22
Opened 2022-01-06 16:31 UTC by Thejus-Paul

Fixes #19 
- Added role validation schema.
- Added edit role pane component.
- Added edit role option to dropdown list.

2022-01-07 08:18 UTC, amaldinesh7 requested changes
@Thejus-Paul _a Please check the comments

2022-01-07 08:18 UTC, amaldinesh7 commented on src/components/EditRole.js
> +import React, { useState } from "react";
Do we need a separate file for edit, since there are very few options in the pane, we can afford the logic for edit inside the addMember pane itself conditionally

2022-01-07 08:18 UTC, amaldinesh7 commented on src/constants.js
> +export const EDIT_ROLE_VALIDATION_SCHEMA = yup.object().shape({
We can remove this once the logic is merged with addMember pane. If you have any doubt regarding it, lemme know.

2022-01-10 08:25 UTC, Thejus-Paul commented on src/constants.js
> +export const EDIT_ROLE_VALIDATION_SCHEMA = yup.object().shape({
@amaldinesh7 I have made some changes. Is this how it should be? Or is there a better way to refactor?

2022-01-11 04:33 UTC, Thejus-Paul commented
@amaldinesh7 _a Please review.

2022-01-11 09:50 UTC, amaldinesh7 commented
@Thejus-Paul _a Please make the UI and code changes as discussed over call.

2022-01-12 07:16 UTC, Thejus-Paul commented
@amaldinesh7 _a Please review.

2022-01-13 07:20 UTC, amaldinesh7 requested changes
@Thejus-Paul _a Please check the comments

2022-01-13 07:20 UTC, amaldinesh7 commented on src/components/index.js
> +    setSelectedMember(user);
Please do this operation first

2022-01-13 07:20 UTC, amaldinesh7 commented on src/components/AddMember.js
> +  useEffect(() => selectedMember &&
Check whether we can directly set state from the props and ret rid of this useeffect

2022-01-13 07:20 UTC, amaldinesh7 commented on src/components/AddMember.js
> +      const payload = selectedMember ? {
move this payload creation part to a separate function

2022-01-19 02:49 UTC, Thejus-Paul commented
@amaldinesh7 _a Please review.

2022-01-19 08:38 UTC, merged